# Build the dev stage of the Dockerfile, and run it with local ports.
version: '3.7'

services:
  vuln-django:
    image: vuln_django
    build:
      context: .
      target: dev
      args:
        - SERVER_PORT=${SERVER_PORT:-8020}
    environment:
      - SERVER_PORT=${SERVER_PORT:-8020}
    ports:
      - ${SERVER_PORT:-8020}:${SERVER_PORT:-8020}
    entrypoint:
      - /opt/app/start-server.sh
