version: 2.1

orbs:
  stackhawk: stackhawk/stackhawk@1.0.1

workflows:
  build-and-scan:
    jobs:
      - stackhawk/hawkscan-local:
          configuration-files: ./stackhawk.yml ./stackhawk-circleci.yml
          docker-network: scan_net
          app-id: 685847dd-0a74-4f02-b4d2-53f2396c93ed
          steps:
            - run:
                name: Build Vulnarable Django
                command: docker build -t vuln_django:latest .
            - run:
                name: Create scan_net Network
                command: docker network create scan_net
            - run:
                name: Run Vulny Django
                command: docker run --detach --network scan_net --name vuln-django --rm vuln_django:latest
